### PR TITLE
Remove all IPV6 listeners in ingress resources with -disable-ipv6 command line 

### LINKED ISSUE #3138: Upgrade to version 2.4.0 with "-disable-ipv6=true" cannot reach upstream.
**Describe the bug**
We've upgraded our nginx-ingress controller from version 2.1.2 to 2.4.0 and included the `-disable-ipv6=true` arg in our deployment manifest. TKGi clusters don't allow IPv6. (see also https://github.com/nginxinc/kubernetes-ingress/issues/2970)

The nginx-ingress pods start but cannot reach any upstream pods. Connections fail with 404s.

We've set debugging to `-v=3` and configured log-format to:
```
log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" ua="$upstream_addr"'
```
Which produces these logs:
```
10.200.57.53 [11/Oct/2022:12:54:45 +0000] TCP 200 5625 1389 0.004 "vault.cluster.example.com"
10.200.57.53 - - [11/Oct/2022:12:54:46 +0000] "POST /v1/auth/kubernetes-cluster/login HTTP/1.1" 404 153 "-" "-" "-" ua="-"
```
On the pods themselves we're still seeing ipv6 listeners configured (along with IPv4 listeners):
```
nginx@nginx-ingress-64556df554-4t44r:/etc/nginx/conf.d$ grep listen vault-vault.conf 
        listen 80;
        listen [::]:80;
        listen unix:/var/lib/nginx/passthrough-https.sock ssl proxy_protocol;
```

**To Reproduce**
1. Update kubernetes-ingress deployment manifest from v2.1.2 to v2.4.0
2. Include `-disable-ipv6=true` argument
3. Update RBAC manifests
4. Deploy manifests
5. Check pod logs.

**Expected behavior**
kubernetes-ingress is able to communicate with upstream pods/services.

**Environment**
* Ingress Controller: v2.4.0
* Kubernetes: v1.23.7
* Kubernetes platform: TKGi
* Using NGINX (no PLUS)

**Additional context**
See also https://github.com/nginxinc/kubernetes-ingress/issues/2970

### PR DESCRIPTION
**Pull request by haywoodsh**
### Proposed changes
When `-disable-ipv6` command line argument is used, remove all IPV6 listeners in upstream deployed with ingress.
Closes #3138 

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by jjngx — APPROVED** [review]

**Review by shaun-nx — APPROVED** [review]

File: internal/configs/ingress_test.go [hunk 1]
```diff
@@ -152,6 +152,25 @@ func TestGenerateNginxCfgWithWildcardTLSSecret(t *testing.T) {
...
+	cafeIngressEx := createCafeIngressEx()
+	isPlus := false
+	configParams := NewDefaultConfigParams(isPlus)
+
+	expected := createExpectedConfigForCafeIngressEx(isPlus)
+	expected.Servers[0].DisableIPV6 = true
+
+	result, warnings := generateNginxCfg(&cafeIngressEx, nil, nil, false, configParams, isPlus, false, &StaticConfigParams{DisableIPV6: true}, false)
+
+	if diff := cmp.Diff(expected, result); diff != "" {
```
[the remark this answers is not in the document]
Comment (haywoodsh) [reply internal/configs/ingress_test.go]: Sounds good! Updated in the latest commit.

File: tests/suite/test_disable_ipv6_ingress.py [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+
+    return DisableIPV6Setup(ingress_controller_endpoint, ingress_name, ingress_host, ic_pod_name, test_namespace)
+
+
+@pytest.mark.ingresses
+class TestDisableIPV6:
+    @pytest.mark.parametrize(
+        "ingress_controller",
+        [
+            pytest.param({"extra_args": ["-disable-ipv6"]}, id="one-additional-cli-args"),
```
Comment (shaun-nx) [inline tests/suite/test_disable_ipv6_ingress.py:92]: What does the `id="one-additional-cli-args"` option do?

**Review by shaun-nx — APPROVED** [review]

File: tests/suite/test_disable_ipv6_ingress.py (hunk 2 above)
Comment (haywoodsh) [reply tests/suite/test_disable_ipv6_ingress.py]: This is just the test ID of the `parametrize` values in pytest. Since I only have one set of values, I have removed the id and let pytest generate it.

**Review by vepatel — APPROVED** [review]
